// export const API_URL = "http://65.1.26.129:9090"; // Replace with your actual API URL http://43.204.109.40:8083
// export const MOCK_API_URL = "http://15.206.65.54:8083/mock"; //'http://43.204.109.40:8083/mock'; //before nginx ready http://43.204.109.40:8086
export const API_URL = "http://13.126.129.245/crmlms"; // Replace with your actual API URL http://43.204.109.40:8083
export const MOCK_API_URL = "http://13.126.129.245/mock"; //'http://43.204.109.40:8083/mock'; //before nginx ready http://43.204.109.40:8086
export const LOGIN_API_URL = "http://13.126.129.245";
// API endpoints

export const categoryListURL = "/api/v1/crm/category";
export const productListURL = "/api/v1/crm/products";
export const taxesListURL = "/api/v1/crm/taxes";
export const addTaxesURL = "/api/v1/crm/tax-class";
export const opportunityAppointmentsURL = "/api/v1/crm/appointments";
export const opportunityQuotationsURL = "/api/v1/crm/quotations";
export const opportunityContactsURL = "/api/v1/crm/contacts";
export const opportunitynotesURL = "/api/v1/crm/notes";
export const profileDetailsURL = "/api/v1/crm/profile-opportunity";
export const taxesURL = "/api/v1/crm/tax";
export const taxClassesListURL = "/api/v1/crm/tax-class";
export const addLeadsURL = "/api/v1/lms/leads";
export const addCompanyDetailsURL = "/api/v1/crm/companydetails";
export const leadDetailsNote = "/api/v1/lms/lead/notes";
export const supportListURL = "/api/v1/crm/ticket";
export const setupNotification = "/api/v1/crm/notification";
export const setupPayment = "/api/v1/crm/paymentsetup";
export const newsAndAnnoucementsURL = "/api/v1/crm/news";
export const setupCountry = "/api/v1/crm/country";
export const setupCurrency = "/api/v1/crm/currency";
export const activityLogs = "/api/v1/crm/activities";
export const adminDashboard = "/api/v1/crm/dashboard/1";
export const customerURL = "/api/v1/crm/customers";
export const viewCustomerURL = "/api/v1/crm/customers/view";
export const LeadListURL = "/api/v1/lms/leads";
export const opportunityListURL = "/api/v1/crm/opportunities";
export const leadDetails = "/api/v1/crm/lead";
export const viewLeadOnclick = "/api/v1/lms/leads/view";
export const expensesURL = "/api/v1/crm/expenses";
export const opportunitiesURL = "/api/v1/crm/opportunities";
export const viewOpportunitiesURL = "/api/v1/crm/opportunities/view";
export const importOpportunitiesURL = "/api/v1/crm/opportunities/import";
export const exportOpportunitiesURL = "/api/v1/crm/opportunities/export";
export const leadDetailsCall = "/api/v1/lms/lead/calls";
export const customerDetailsURL = "/api/v1/crm/customerdetails";
export const customerDetailsCalls = "/api/v1/crm/calls";
export const customerDetailsinvoice = "/api/v1/crm/order-details";
export const customerDetailsTickets = "/api/v1/crm/tickets";
export const customerDetailsDocsFiles = "/api/v1/crm/documents";
export const customerDetail = "/api/v1/crm/customers/view";
export const customerDetailGet = "/api/v1/crm/customerdetails";
export const addTicketUrl = "/api/v1/crm/tickets";
export const leadUrl = "/api/v1/lms/leads";
export const customerDetailsInvoices = "/api/v1/crm/invoice";
export const profileURL = "/api/v1/crm/user-profile";
export const leadListingDelete = "/api/v1/lms/leads";
export const customerListingDelete = "/api/v1/crm/customers"
export const leadConversionURL = "/api/v1/crm/lead-conversion";
export const customerConversionURL = "/api/v1/crm/customer-conversion";
export const opportunityConversionURL = "/api/v1/crm/opportunity-conversion";
export const authRefreshURL = "/api/v1/auth/refresh" //dummy URL replace with actual URL when provided
export const leadAddNotes = "/api/v1/lms/notes";
export const leadEditNotes = "/api/v1/lms/lead/notes"


